alias acc="activator clean compile"
alias acr="activator clean run"
alias act="activator clean test"
alias acto='function __activatorTestOnly() { eval "activator clean \"testOnly $*\""; unset -f __activatorTestOnly; }; __activatorTestOnly'
alias actpub="activator clean test publishLocal"
alias acpub="activator clean publishLocal"
alias a2k="activator clean \"run 2000\""
alias a3k="activator clean \"run 3000\""
alias a4k="activator clean \"run 4000\""
alias a5k="activator clean \"run 5000\""
alias a6k="activator clean \"run 6000\""
alias a7k="activator clean \"run 7000\""
alias a8k="activator clean \"run 8000\""
alias a9k="activator clean \"run 9000\""
alias a10k="activator clean \"run 10000\""
alias a11k="activator clean \"run 11000\""
alias a12k="activator clean \"run 12000\""
alias a13k="activator clean \"run 13000\""
alias a14k="activator clean \"run 14000\""
alias a15k="activator clean \"run 15000\""
alias gpl="git pull"
alias gst="git status"
alias gpushm="git push origin master"
alias gpushb="git push origin HEAD"
alias glg="git lg1a"
alias gdf="git diff"
alias gad="git add ."
alias sss="ssssssssss_settitle"
alias gchm="git checkout master"
alias gcom='function __gcm() { eval "git commit -m \"$*\""; unset -f __gcm; }; __gcm'
alias gaddfile='function __gaf() { eval "git add $*"; unset -f __gaf; }; __gaf'
alias gdifffile='function __gdfile() { eval "git diff $*"; unset -f __gdfile; }; __gdfile'
alias gchfile='function __gchfile() { eval "git checkout $*"; unset -f __gchfile; }; __gchfile'
alias gnewbra='function __gnewbra() { eval "git checkout -b $*"; unset -f __gnewbra; }; __gnewbra'
